apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: super-insecure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ko://github.com/nsmith5/super-insecure
        args:
        - "serve"
        ports:
        - containerPort: 8080
  
